### PR TITLE
Feat : Toast Component

### PR DESCRIPTION
**Pull request by anuj-kumary**

### CODE REVIEW

**Review by thegeorgenikhil — APPROVED** [review]
Font weights 600 400 seems to be recurring ones better to make them variables
Approving this!

**Comment by anuj-kumary** [comment]
> Font weights 600 400 seems to be recurring ones better to make them variables Approving this!
On text utility components I implement font-weight utility also now I'm using that class here

**Review by hrishi82 — APPROVED** [review]
Looks good

**Review by varnita619 — APPROVED** [review]
looks good

**Pull request merged**
