### PR TITLE
Image and input

### PR DESCRIPTION
**Pull request by anuj-kumary**

### CODE REVIEW

**Comment by ravikumar1002** [comment]
Nice naming done for the CSS classes. Overall looks great.

**Review by ravikumar1002 — CHANGES_REQUESTED** [review]
everything looks great. one suggestion

**Comment by anuj-kumary** [comment]
> everything looks great. one suggestion, try to give color variable (root)

I already defined root color in my style.css

**Comment by ravikumar1002** [comment]
> > everything looks great. one suggestion, try to give color variable (root)
> 
> I already defined root color in my style.css

ohh sorry, that was a badge color, I did not focused on variable name

**Review by ravikumar1002 — APPROVED** [review]
Everything is good,  class name are impressive.

**Comment by anuj-kumary** [comment]
Adding more input property

**Pull request closed without merging**
